spring.application.name=Spring_Security
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.ldap.embedded.port=8389
spring.ldap.embedded.ldif=classpath:schema.ldif
spring.ldap.embedded.base-dn=dc=springframework,dc=org
spring.ldap.base=${spring.ldap.embedded.base-dn}